export const actionTypes = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    FETCH_PRODUCT: "FETCH_PRODUCT",
    SET_ALL_PRODUCTS: "SET_ALL_PRODUCTS",
    GET_SELECTED_PRODUCT: "GET_SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT"
} 